---
id: tokyorubykaigi12
base_name: slide
tags: []
presentation_date:
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri:
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
